require("silly.plugins-setup")
require("silly.core.options")
require("silly.core.keymaps")
require("silly.core.colorscheme")
require("silly.plugins.lualine")
require("silly.plugins.telescope")
require("silly.plugins.comment")
require("silly.plugins.nvim-tree")
